### ISSUE TITLE
run  error

### ISSUE THREAD

**Issue by zhangabner** [ngessert/isic2019#1]
(tensorflow1.6) newwen@newwen-ECQ3-0:~/Documents/isic/isic2019-master$ python train.py example 2019.test_effb0_ss gpu0
['/home/newwen/Documents/isic/isic2019-master/images/official/']
/home/newwen/anaconda3/envs/tensorflow1.6/lib/python3.5/site-packages/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/newwen/anaconda3/envs/tensorflow1.6/lib/python3.5/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
nan
Len ham 0
Train
(20252,)
(20252,)
(20257,)
(20257,)
(20251,)
Val
(5079,)
(5079,)
(5074,)
(5074,)
(5080,)
Devices to use: 0
Evaluating on validation set during training.
CV set 0
cuda:0
Balance 9
Traceback (most recent call last):
  File "train.py", line 204, in <module>
    class_weights_ = 1.0/np.mean(mdlParams['labels_array'][indices_ham,:8],axis=0)
IndexError: too many indices for array

**Comment by 9ayhub** [comment]
I have the same problem as you. Have you solved it?

**Comment by ngessert** [comment]
This is probably caused by a mismatch between actual folder names and names provided in the cfg files.  I noticed that my readme example used a different naming than the standard config files. If you named your folder "official" it should work now.

**Comment by 9ayhub** [comment]
> This is probably caused by a mismatch between actual folder names and names provided in the cfg files. I noticed that my readme example used a different naming than the standard config files. If you named your folder "official" it should work now.

Thanks for your answer, but I still can't run this program successfully. Could you take a screenshot of your dataset and label file, Or send your data set and label to me?My email address is 354787627@qq.com. Thank you!

**Comment by ngessert** [comment]
The dataset and label files are the ones from the challenge providers. The images are just resized, as described in the paper, and the label file is the original one. Please check whether the paths to the image and label folder are correct (mdlParams['dataDir']). You can change the base path in pc_cfgs and the path to the folders in the cfgs. The full paths should look something like this: /home/Gessert/data/isic/2019/images/official/ISIC_0000000.jpg and /home/Gessert/data/isic/2019/labels/official/ISIC_2019_Training_GroundTruth.csv

**Comment by LezardValeth97** [comment]
I have the same error and also set paths correctly, but I still got this problem, too!

**Comment by LezardValeth97** [comment]
Does anyone solve this problem? I try many ways including changing the paths, but it still doesn't work!

**Comment by ngessert** [comment]
Unfortunately, it is hard for me to find the reason remotely. You could try debugging the code and check whether, e.g., mdlParams['labels_array'], mdlParams['labels_list'], mdlParams['im_paths'], and mdlParams['labels_dict'] are created correctly (if not, they are empty).

You could start at the definition of mdlParams['labels_dict'].

**Comment by LezardValeth97** [comment]
For me to work, I replace the line 26 in file "cfgs folder" into mdlParams['file_ending'] = '.jpg', at first it was png, hope it helps you guys!

Anyway, thank you for your answer!

**Comment by LezardValeth97** [comment]
Hello, I have a question regarding to the Challenge cause it confuses me, how do we calculate Balanced Multiclass Accuracy?

Thank you,
